#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@dnsfilter[-1]
	add ucitrack dnsfilter
	set ucitrack.@dnsfilter[-1].init=dnsfilter
	commit ucitrack
EOF

chmod 0755 /etc
rm -f /tmp/luci-indexcache
exit 0
